name: story_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  flutter_native_splash: ^2.1.0
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.2
  get: 4.6.1
  moor_flutter: 4.0.0
  image_picker: 0.8.4+10
  intl: 0.17.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  

  moor_generator: 4.6.0+1
  build_runner: 2.1.7
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

  

flutter: 
  uses-material-design: true

flutter_native_splash:
    color: "#FFFFFF" 
    image: assets/icon/icon.png
    android: true
    ios: true
    web: false  

flutter_icons: 
  android: launcher_icon
  image_path: assets/icon/icon.png
  ios: true